sudo: false
language: node_js
node_js:
  - "node"
  - "iojs"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"

before_script:
  - npm install -g gulp bower mocha
  - bower install
  - mysql -u root -e "CREATE DATABASE bhima_test;"
  - mysql -u root -e "CREATE USER 'bhima_test'@'%' IDENTIFIED BY 'HISCongo2013';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'bhima'@'localhost' WITH GRANT OPTION;"

cache:
  directories:
    - node_modules/
    - client/vendor

# set the clone depth to a low value 
git:
  depth: 3

# make sure we aren't caching verbose output from NPM
before_cache:
  - rm -f npm-debug.log

services:
  - mysql
